/*
 * PyrxSynapseModule.h
 * @pyrx/synapse-react-native — iOS TurboModule bridge.
 *
 * Declares the ObjC++ TurboModule that bridges JS calls into the Swift
 * implementation (`PyrxSynapseImpl.swift`) which in turn wraps the
 * `Pyrx` actor from the published `PYRXSynapse` SPM/CocoaPods package.
 *
 * `PyrxSynapseSpec.h` is generated by RN's codegen from
 * `src/NativePyrxSynapse.ts` at build time (xcodebuild runs the codegen
 * script before compiling pods). It declares the `NativePyrxSynapseSpec`
 * protocol that this class conforms to — so any method we miss or whose
 * signature we get wrong is a compile-time error, not a runtime crash.
 *
 * Why a separate Swift impl file?
 * --------------------------------
 * The bridge must be ObjC++ (`.mm`) because TurboModule's `getTurboModule`
 * returns a C++ shared_ptr — that's not callable from pure Swift. But
 * the actual work (calling into PYRXSynapse, which is a Swift actor)
 * belongs in Swift for ergonomic async/await and the actor isolation
 * the SDK already enforces. So: thin `.mm` for the codegen-protocol
 * conformance + boxing/unboxing primitives, thicker `.swift` for the
 * SDK calls. The `.mm` calls `[[PyrxSynapseImpl shared] ...]` for each
 * method.
 */

#import <PyrxSynapseSpec/PyrxSynapseSpec.h>

@interface PyrxSynapseModule : NSObject <NativePyrxSynapseSpec>

@end
