/*
 * PyrxSynapseModule.h
 * @pyrx/synapse-react-native — iOS TurboModule bridge.
 *
 * Declares the ObjC++ TurboModule that bridges JS calls into the Swift
 * implementation (`PyrxSynapseImpl.swift`) which in turn wraps the
 * `Pyrx` actor from the published `PYRXSynapse` SPM/CocoaPods package.
 *
 * `PyrxSynapseSpec.h` is generated by RN's codegen from
 * `src/NativePyrxSynapse.ts` at build time (xcodebuild runs the codegen
 * script before compiling pods). It declares the `NativePyrxSynapseSpec`
 * protocol that this class conforms to — so any method we miss or whose
 * signature we get wrong is a compile-time error, not a runtime crash.
 *
 * Why a separate Swift impl file?
 * --------------------------------
 * The bridge must be ObjC++ (`.mm`) because TurboModule's `getTurboModule`
 * returns a C++ shared_ptr — that's not callable from pure Swift. But
 * the actual work (calling into PYRXSynapse, which is a Swift actor)
 * belongs in Swift for ergonomic async/await and the actor isolation
 * the SDK already enforces. So: thin `.mm` for the codegen-protocol
 * conformance + boxing/unboxing primitives, thicker `.swift` for the
 * SDK calls. The `.mm` calls `[[PyrxSynapseImpl shared] ...]` for each
 * method.
 *
 * Why we extend RCTEventEmitter (Phase 9.2.1)
 * -------------------------------------------
 * Phase 9.2.1 introduces five observer events forwarded from the native
 * `Pyrx.shared.events()` AsyncStream into JS via NativeEventEmitter:
 *   - "pyrx:push:received"
 *   - "pyrx:push:click"
 *   - "pyrx:push:received-cold-start"  (new in 0.2.0)
 *   - "pyrx:queue:drained"
 *   - "pyrx:identity:changed"          (new in 0.2.0)
 * Extending `RCTEventEmitter` gives us `sendEventWithName:body:` plus the
 * `addListener` / `removeListeners` / `supportedEvents` plumbing the JS
 * `new NativeEventEmitter(NativePyrxSynapse)` constructor expects. Our
 * codegen protocol's `addListener:` and `removeListeners:` methods
 * delegate to `super` (the RCTEventEmitter implementations) so the JS
 * side sees one consistent listener-count contract.
 *
 * The Swift impl owns the AsyncStream subscription itself — see
 * `PyrxSynapseImpl.startObservingPyrxEvents` for the lifecycle. The
 * `.mm` simply wires `[PyrxSynapseImpl shared].emitter = self;` on
 * `startObserving` so the impl can call back via `sendEventWithName:`.
 */

#import <PyrxSynapseSpec/PyrxSynapseSpec.h>
#import <React/RCTEventEmitter.h>

@interface PyrxSynapseModule : RCTEventEmitter <NativePyrxSynapseSpec>

@end
