/*
 * PyrxSynapseModule.mm
 * @pyrx/synapse-react-native — iOS TurboModule bridge implementation.
 *
 * Glue between the codegen-generated `NativePyrxSynapseSpec` protocol
 * and the Swift `PyrxSynapseImpl` class (which is where the real work
 * happens — see PyrxSynapseImpl.swift).
 *
 * Pattern overview
 * ----------------
 * Every protocol method here does the same three things:
 *   1. Unbox the ObjC types the codegen handed us into Swift-friendly
 *      types (NSString → String, NSNumber → Bool/Int/Double, etc.).
 *   2. Call the corresponding method on `[PyrxSynapseImpl shared]`,
 *      forwarding the RN promise resolver/rejecter closures.
 *   3. The Swift side fulfills the resolver on success or invokes the
 *      rejecter with a typed `code` string + message on failure.
 *
 * Error code contract
 * -------------------
 * The Swift side maps every PyrxError case to one of:
 *   "not_initialized" | "permission_denied" | "network_error" |
 *   "invalid_argument" | "internal_error"
 * The JS surface (`src/index.ts`, PR-2) translates these into the
 * SynapseError class.
 *
 * Why we don't expose `handleDeviceToken` to JS
 * --------------------------------------------
 * APNs registration callbacks fire on the AppDelegate, before the JS
 * bridge is alive on cold-start launches. The base class
 * `PYRXSynapseAppDelegate` (PyrxSynapseAppDelegate.swift in this same
 * directory) intercepts those callbacks and forwards them to the
 * underlying `Pyrx.shared.handleDeviceToken` automatically. The JS
 * layer never sees the token — it just observes the resulting
 * device-registered telemetry via the dashboard.
 *
 * NativeEventEmitter integration (Phase 9.2.1)
 * --------------------------------------------
 * This class extends `RCTEventEmitter` so JS subscribers using
 * `new NativeEventEmitter(NativePyrxSynapse)` receive events from the
 * native `Pyrx.shared.events()` AsyncStream. The actual subscription
 * is owned by `PyrxSynapseImpl` (Swift); we install a back-reference
 * to `self` (the emitter) in `startObserving` so the impl can call
 * `sendEventWithName:body:` for each PyrxEvent received from the SDK.
 *
 * Lifecycle:
 *   - JS calls `new NativeEventEmitter(NativePyrxSynapse)`. The first
 *     `addListener` triggers `startObserving` → we plug the emitter
 *     into the Swift impl and the impl starts collecting the SDK
 *     AsyncStream into a held `Task`.
 *   - The Swift impl forwards each event by calling
 *     `sendEventWithName:body:` on this emitter (via the back-ref).
 *   - The last `removeListeners` decrement triggers `stopObserving` →
 *     we cancel the impl's collecting Task and clear the back-ref.
 *
 * Multi-bridge note: in dev with Metro fast-reload, the RN bridge can
 * be torn down and re-created. `RCTInvalidating` (which RCTEventEmitter
 * conforms to) calls `invalidate` on bridge teardown; we forward to
 * the impl so its held Task is cancelled before a new bridge instance
 * attaches.
 */

#import "PyrxSynapseModule.h"
// Forward declaration of the Swift impl class. The bridge header
// (generated by SPM/Xcode as `PyrxSynapseRN-Swift.h`) defines the real
// signatures.
#if __has_include("PyrxSynapseRN-Swift.h")
#import "PyrxSynapseRN-Swift.h"
#else
#import <PyrxSynapseRN/PyrxSynapseRN-Swift.h>
#endif

@implementation PyrxSynapseModule

RCT_EXPORT_MODULE()

// RCTEventEmitter requires a hint about main-queue setup. We return YES
// because PyrxSynapseImpl is @MainActor-isolated — the bridge attachment
// must happen on the main queue to satisfy actor isolation.
+ (BOOL)requiresMainQueueSetup {
  return YES;
}

#pragma mark - NativeEventEmitter (RCTEventEmitter)

// The closed event-name catalogue. RN throws at runtime if we attempt
// to emit a name not listed here, AND if JS subscribes to a name not
// listed here. Must stay in sync with `src/events.ts`'s SynapseEventMap.
//
// Five events as of Phase 9.2.1 (0.2.0 — was three in 0.1.x):
//   - pyrx:push:received              foreground delivery
//   - pyrx:push:click                 warm-start tap
//   - pyrx:push:received-cold-start   cold-start launch from a tap (NEW)
//   - pyrx:queue:drained              event-queue successful flush
//   - pyrx:identity:changed           identify/alias/logout transition (NEW)
- (NSArray<NSString *> *)supportedEvents {
  return @[
    @"pyrx:push:received",
    @"pyrx:push:click",
    @"pyrx:push:received-cold-start",
    @"pyrx:queue:drained",
    @"pyrx:identity:changed",
  ];
}

// Called by RCTEventEmitter when the first JS listener is added (across
// any of supportedEvents). This is the cue to start the native-side
// AsyncStream subscription; doing it lazily means apps that never
// subscribe pay zero observer overhead.
- (void)startObserving {
  [[PyrxSynapseImpl shared] startObservingPyrxEventsWithEmitter:self];
}

// Called by RCTEventEmitter when the last listener is removed. Cancel
// the Swift impl's collecting Task and drop the emitter back-ref so
// the impl doesn't retain us through a teardown.
- (void)stopObserving {
  [[PyrxSynapseImpl shared] stopObservingPyrxEvents];
}

// RCTInvalidating contract — fired on bridge teardown (Metro reload,
// app termination). Cancels the Swift impl's collecting Task so a new
// bridge instance gets a clean slate. Calling super is required by the
// NS_REQUIRES_SUPER annotation on RCTEventEmitter.invalidate.
- (void)invalidate {
  [[PyrxSynapseImpl shared] stopObservingPyrxEvents];
  [super invalidate];
}

#pragma mark - Lifecycle

- (void)initialize:(JS::NativePyrxSynapse::SynapseInitConfig &)config
           resolve:(RCTPromiseResolveBlock)resolve
            reject:(RCTPromiseRejectBlock)reject {
  // Unbox the codegen struct into a plain NSDictionary the Swift side
  // can iterate at runtime. Optional fields (`baseUrl`, `logLevel`,
  // `maxQueueSize`) come through as nil when omitted by the JS caller.
  NSMutableDictionary *cfg = [NSMutableDictionary new];
  cfg[@"workspaceId"] = config.workspaceId();
  cfg[@"apiKey"] = config.apiKey();
  cfg[@"environment"] = config.environment();
  if (config.baseUrl().has_value()) {
    cfg[@"baseUrl"] = config.baseUrl().value();
  }
  if (config.logLevel().has_value()) {
    cfg[@"logLevel"] = config.logLevel().value();
  }
  if (config.maxQueueSize().has_value()) {
    cfg[@"maxQueueSize"] = @(config.maxQueueSize().value());
  }
  [[PyrxSynapseImpl shared] initializeWithConfig:cfg resolver:resolve rejecter:reject];
}

- (void)setLogLevel:(NSString *)level
            resolve:(RCTPromiseResolveBlock)resolve
             reject:(RCTPromiseRejectBlock)reject {
  [[PyrxSynapseImpl shared] setLogLevelWithLevel:level resolver:resolve rejecter:reject];
}

- (void)debugInfo:(RCTPromiseResolveBlock)resolve
           reject:(RCTPromiseRejectBlock)reject {
  [[PyrxSynapseImpl shared] debugInfoWithResolver:resolve rejecter:reject];
}

#pragma mark - Identity

- (void)identify:(NSString *)externalId
      traitsJson:(NSString * _Nullable)traitsJson
         resolve:(RCTPromiseResolveBlock)resolve
          reject:(RCTPromiseRejectBlock)reject {
  [[PyrxSynapseImpl shared] identifyWithExternalId:externalId
                                        traitsJson:traitsJson
                                          resolver:resolve
                                          rejecter:reject];
}

- (void)alias:(NSString *)newExternalId
      resolve:(RCTPromiseResolveBlock)resolve
       reject:(RCTPromiseRejectBlock)reject {
  [[PyrxSynapseImpl shared] aliasWithNewExternalId:newExternalId
                                          resolver:resolve
                                          rejecter:reject];
}

- (void)logout:(RCTPromiseResolveBlock)resolve
        reject:(RCTPromiseRejectBlock)reject {
  [[PyrxSynapseImpl shared] logoutWithResolver:resolve rejecter:reject];
}

#pragma mark - Events

- (void)track:(NSString *)eventName
propertiesJson:(NSString * _Nullable)propertiesJson
      resolve:(RCTPromiseResolveBlock)resolve
       reject:(RCTPromiseRejectBlock)reject {
  [[PyrxSynapseImpl shared] trackWithEventName:eventName
                                propertiesJson:propertiesJson
                                      resolver:resolve
                                      rejecter:reject];
}

- (void)screen:(NSString *)screenName
propertiesJson:(NSString * _Nullable)propertiesJson
       resolve:(RCTPromiseResolveBlock)resolve
        reject:(RCTPromiseRejectBlock)reject {
  [[PyrxSynapseImpl shared] screenWithScreenName:screenName
                                  propertiesJson:propertiesJson
                                        resolver:resolve
                                        rejecter:reject];
}

#pragma mark - Push

- (void)requestPushPermission:(JS::NativePyrxSynapse::PushPermissionOptions &)options
                      resolve:(RCTPromiseResolveBlock)resolve
                       reject:(RCTPromiseRejectBlock)reject {
  // Default each flag to true (matches the iOS SDK's
  // requestPushPermission default and the typical FCM flow on Android).
  BOOL alert = options.alert().has_value() ? options.alert().value() : YES;
  BOOL sound = options.sound().has_value() ? options.sound().value() : YES;
  BOOL badge = options.badge().has_value() ? options.badge().value() : YES;
  [[PyrxSynapseImpl shared] requestPushPermissionWithAlert:alert
                                                     sound:sound
                                                     badge:badge
                                                  resolver:resolve
                                                  rejecter:reject];
}

- (void)getPushPermissionStatus:(RCTPromiseResolveBlock)resolve
                         reject:(RCTPromiseRejectBlock)reject {
  [[PyrxSynapseImpl shared] getPushPermissionStatusWithResolver:resolve rejecter:reject];
}

#pragma mark - Privacy

- (void)setTrackingEnabled:(BOOL)enabled
                   resolve:(RCTPromiseResolveBlock)resolve
                    reject:(RCTPromiseRejectBlock)reject {
  [[PyrxSynapseImpl shared] setTrackingEnabledWithEnabled:enabled
                                                 resolver:resolve
                                                 rejecter:reject];
}

- (void)deleteUser:(RCTPromiseResolveBlock)resolve
            reject:(RCTPromiseRejectBlock)reject {
  [[PyrxSynapseImpl shared] deleteUserWithResolver:resolve rejecter:reject];
}

#pragma mark - NativeEventEmitter symmetry

// addListener / removeListeners are required-by-protocol on TurboModules
// that emit events. Since we now inherit from RCTEventEmitter, the
// superclass provides full implementations that count listeners and
// drive `startObserving` / `stopObserving`. We forward to super so the
// codegen-protocol conformance is satisfied AND the parent class's
// bookkeeping fires.

- (void)addListener:(NSString *)eventType {
  [super addListener:eventType];
}

- (void)removeListeners:(double)count {
  [super removeListeners:count];
}

#pragma mark - TurboModule plumbing

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params {
  return std::make_shared<facebook::react::NativePyrxSynapseSpecJSI>(params);
}

+ (NSString *)moduleName {
  // Must match the string passed to TurboModuleRegistry.getEnforcing
  // in src/NativePyrxSynapse.ts.
  return @"PyrxSynapse";
}

@end
