// swift-tools-version:5.9
//
// Package.swift — Swift Package Manager test harness for the pure-Swift
// portions of `PyrxSynapseImpl` and its helpers.
//
// Why a separate SwiftPM package (and not an Xcode test target inside
// the example app's workspace)?
// ----------------------------------------------------------------------
// 1. The example app is an Expo Dev Build. `examples/SynapseRNDemo/ios/`
//    does NOT exist on disk — it is regenerated by `npx expo prebuild`.
//    Any test target added inside that generated workspace would be
//    wiped on the next prebuild. SwiftPM lives outside that lifecycle.
//
// 2. `swift test` requires neither Xcode nor CocoaPods. It runs on every
//    developer's machine and on every CI runner with Swift 5.9+ without
//    a Pods install (which on Apple Silicon + Ruby 2.x is fragile —
//    see PR body for the ffi-1.15.5 caveat).
//
// 3. The PYRXSynapse iOS SDK supports SPM as a first-class distribution,
//    so we can depend on it directly via git/version pinning. No
//    framework binary bundling needed.
//
// Scope of these tests
// --------------------
// Pure helpers from `PyrxSynapseImplHelpers.swift` (JSON marshalling,
// status string mapping, error contract mapping, log-level parsing,
// authorization option assembly, IdentityResult → dict). Plus the
// `PyrxWrapper` protocol and `ProductionPyrxWrapper` forwarding shape.
//
// Tests that exercise the full `PyrxSynapseImpl` bridge — including
// `RCTPromiseResolveBlock` / `RCTPromiseRejectBlock` mechanics — require
// the React framework which is not available via SPM. Those run via
// `xcodebuild test` inside the example app's prebuilt Xcode workspace,
// gated on a CI job that performs `expo prebuild` + `pod install` first.
// See `.github/workflows/ci.yml`.
//
// How to run locally
// ------------------
//   cd ios/PyrxSynapseRN/Tests
//   swift test
//
// First run downloads the PYRXSynapse SPM dep (~30s); subsequent runs
// reuse the resolved package.
//

import PackageDescription

let package = Package(
    name: "PyrxSynapseRNTests",
    platforms: [
        // PYRXSynapse iOS floor is 14.0; PyrxSynapseRN podspec pins iOS
        // 14.0. Match here so the SPM resolver doesn't complain.
        .iOS(.v14),
        .macOS(.v11), // For host-side `swift test` execution
    ],
    products: [
        // Library target so the test target can link the source files.
        .library(name: "PyrxSynapseRNCore", targets: ["PyrxSynapseRNCore"]),
    ],
    dependencies: [
        // PYRXSynapse iOS SDK — pinned matching the podspec's `>= 0.1.1`.
        // SwiftPM does NOT support `>= X` syntax, so we use
        // `.upToNextMajor(from: "0.1.1")` which accepts every
        // 0.x.y release ≥ 0.1.1 but blocks a future 1.0 with breaking
        // changes (same intent as the podspec pin).
        .package(
            url: "https://github.com/PYRX-Tech/pyrx-synapse-ios.git",
            from: "0.1.1"
        ),
    ],
    targets: [
        // Source target — symlinks the two files we want under test.
        // Symlinks (not copies) so edits in the canonical
        // `ios/PyrxSynapseRN/` location flow straight into the SPM
        // build without a sync step.
        .target(
            name: "PyrxSynapseRNCore",
            dependencies: [
                .product(name: "PYRXSynapse", package: "pyrx-synapse-ios"),
            ],
            path: "Sources/PyrxSynapseRNCore"
        ),
        .testTarget(
            name: "PyrxSynapseRNCoreTests",
            dependencies: ["PyrxSynapseRNCore"],
            path: "Tests/PyrxSynapseRNCoreTests"
        ),
    ]
)
